disabled_rules:
  - large_tuple
  - trailing_whitespace
  - todo
  - opening_brace
  - nesting
included:
  - iCookNetworking
  - iCookUI
  - iCook
excluded:
  - Pods
  - .build
  - .derivedData
  - iCookUI/iCookUITests
  - iCookNetworking/iCookNetworkingTests
  - iCook/iCookTests
line_length: 140
file_length:
  warning: 200
  error: 250
identifier_name:
  allowed_symbols: "_"
  min_length: 2
  max_length:
    warning: 90
    error: 1000
  excluded:
    - id
    - x
    - y